# Generated by Django 6.0.7 on 2026-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='id_externo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
