# Generated by Django 6.0.7 on 2026-07-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participante_id_externo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=20)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
