# Generated by Django 6.0.7 on 2026-07-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_temporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('CLAUSURA', 'Clausura'), ('COPA_ARG', 'Copa Argentina'), ('SUPERCOPA', 'Supercopa')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
            ],
        ),
    ]
