# Generated by Django 6.0.7 on 2026-07-21 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_general', models.CharField(choices=[('LIGA', 'Liga'), ('COPA', 'Copa'), ('SUPERCOPA', 'Supercopa'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plantillacompetencia')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_participantes', models.IntegerField(default=0)),
                ('cantidad_zonas', models.IntegerField(default=0)),
                ('clasificados', models.IntegerField(default=0)),
                ('cantidad_partidos_boleta', models.IntegerField(default=15)),
                ('frecuencia_dias', models.IntegerField(default=7)),
                ('maximo_locales', models.IntegerField(default=11)),
                ('cantidad_ascensos', models.IntegerField(default=0)),
                ('cantidad_descensos', models.IntegerField(default=0)),
                ('tiene_playoff', models.BooleanField(default=False)),
                ('tiene_penales', models.BooleanField(default=False)),
                ('permite_equipos', models.BooleanField(default=False)),
                ('usa_tabla', models.BooleanField(default=True)),
                ('usa_af', models.BooleanField(default=True)),
                ('usa_av', models.BooleanField(default=True)),
                ('usa_da', models.BooleanField(default=True)),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FECHA', 'Fecha'), ('RONDA', 'Ronda'), ('PLAYOFF', 'Playoff'), ('FINAL', 'Final'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competencia')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('es_nuevo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participante')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
            ],
            options={
                'unique_together': {('participante', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('ACTIVO', 'Activo'), ('ELIMINADO', 'Eliminado'), ('CLASIFICADO', 'Clasificado'), ('CAMPEON', 'Campeón'), ('SUBCAMPEON', 'Subcampeón')], default='INSCRIPTO', max_length=20)),
                ('resultado_final', models.CharField(blank=True, default='', max_length=50)),
                ('posicion_final', models.IntegerField(blank=True, null=True)),
                ('clasificado_desde', models.CharField(blank=True, default='', max_length=100)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competencia')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
        ),
    ]
