# Generated by Django 6.0.7 on 2026-07-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_calendarioreal_equiporeal_partidoreal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarioreal',
            options={'verbose_name': 'Calendario Real', 'verbose_name_plural': 'Calendarios Reales'},
        ),
        migrations.AlterModelOptions(
            name='equiporeal',
            options={'verbose_name': 'Equipo Real', 'verbose_name_plural': 'Equipos Reales'},
        ),
        migrations.AlterModelOptions(
            name='partidoreal',
            options={'verbose_name': 'Partido Real', 'verbose_name_plural': 'Partidos Reales'},
        ),
        migrations.CreateModel(
            name='InstanciaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntua', models.BooleanField(default=True)),
                ('es_penal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instanciacompetencia')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partidoreal')),
            ],
            options={
                'verbose_name': 'Instancia Partido',
                'verbose_name_plural': 'Instancias Partido',
                'unique_together': {('instancia', 'partido')},
            },
        ),
    ]
