# Generated by Django 6.0.7 on 2026-07-22 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_calendarioreal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('L', 'Local'), ('E', 'Empate'), ('V', 'Visitante')], max_length=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('instancia_partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instanciapartido')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'unique_together': {('participante_temporada', 'instancia_partido')},
            },
        ),
    ]
