# Generated by Django 6.0.7 on 2026-07-22 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pronostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_real', models.CharField(max_length=1)),
                ('acierto', models.BooleanField(default=False)),
                ('puntos', models.IntegerField(default=0)),
                ('pronostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pronostico')),
            ],
            options={
                'verbose_name': 'Resultado Pronóstico',
                'verbose_name_plural': 'Resultados Pronóstico',
            },
        ),
    ]
