# Generated by Django 6.0.7 on 2026-07-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resultadopronostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenParticipanteInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_evaluados', models.IntegerField(default=0)),
                ('af', models.IntegerField(default=0)),
                ('av', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instanciacompetencia')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Resumen Participante Instancia',
                'verbose_name_plural': 'Resumenes Participante Instancia',
                'unique_together': {('participante_temporada', 'instancia')},
            },
        ),
    ]
