# Generated by Django 6.0.7 on 2026-07-22 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_resumenparticipanteinstancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_local', models.IntegerField(default=0)),
                ('af_visitante', models.IntegerField(default=0)),
                ('av_local', models.IntegerField(default=0)),
                ('av_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instanciacompetencia')),
                ('participante_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfrentamientos_local', to='core.participantetemporada')),
                ('participante_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfrentamientos_visitante', to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Enfrentamiento',
                'verbose_name_plural': 'Enfrentamientos',
                'unique_together': {('instancia', 'participante_local', 'participante_visitante')},
            },
        ),
    ]
