# Generated by Django 6.0.7 on 2026-07-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_enfrentamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='puntos_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='puntos_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='resultado',
            field=models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('VISITANTE', 'Visitante'), ('EMPATE', 'Empate')], default='', max_length=20),
        ),
    ]
