# Generated by Django 6.0.7 on 2026-07-22 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tablacompetencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('af', models.IntegerField(default=0)),
                ('av', models.IntegerField(default=0)),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
            ],
            options={
                'verbose_name': 'Tabla Temporada',
                'verbose_name_plural': 'Tablas Temporada',
                'unique_together': {('participante_temporada', 'temporada')},
            },
        ),
    ]
