# Generated by Django 6.0.7 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tablatemporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablatemporada',
            name='posicion',
            field=models.IntegerField(default=0),
        ),
    ]
