# Generated by Django 6.0.7 on 2026-07-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tablatemporada_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('NINGUNO', 'Ninguno'), ('LIBERTADORES', 'Libertadores'), ('SUDAMERICANA', 'Sudamericana'), ('ASCENSO', 'Ascenso'), ('DESCENSO', 'Descenso'), ('REPECHAJE', 'Repechaje')], default='NINGUNO', max_length=20)),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
            ],
            options={
                'verbose_name': 'Resultado Temporada',
                'verbose_name_plural': 'Resultados Temporada',
                'unique_together': {('participante_temporada', 'temporada')},
            },
        ),
    ]
