# Generated by Django 6.0.7 on 2026-07-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_resultadotemporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(choices=[('ASCENSO', 'Ascenso'), ('DESCENSO', 'Descenso'), ('MANTIENE', 'Mantiene')], max_length=20)),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.categoria')),
                ('categoria_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.categoria')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temporada')),
            ],
            options={
                'verbose_name': 'Movimiento Categoria',
                'verbose_name_plural': 'Movimientos Categoria',
                'unique_together': {('participante_temporada', 'temporada')},
            },
        ),
    ]
