# Generated by Django 6.0.7 on 2026-07-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_movimientocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competencia')),
            ],
            options={
                'verbose_name': 'Grupo Competencia',
                'verbose_name_plural': 'Grupos Competencia',
                'unique_together': {('competencia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupocompetencia')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Participacion Grupo',
                'verbose_name_plural': 'Participaciones Grupo',
                'unique_together': {('grupo', 'participante_temporada')},
            },
        ),
    ]
