# Generated by Django 6.0.7 on 2026-07-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_grupocompetencia_participaciongrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('pj', models.IntegerField(default=0)),
                ('pg', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('af', models.IntegerField(default=0)),
                ('av', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupocompetencia')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Tabla Grupo',
                'verbose_name_plural': 'Tablas Grupo',
                'unique_together': {('grupo', 'participante_temporada')},
            },
        ),
    ]
