# Generated by Django 6.0.7 on 2026-07-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tablagrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[('CLASIFICADO', 'Clasificado'), ('ELIMINADO', 'Eliminado')], max_length=20)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupocompetencia')),
                ('participante_temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Clasificacion Grupo',
                'verbose_name_plural': 'Clasificaciones Grupo',
                'unique_together': {('grupo', 'participante_temporada')},
            },
        ),
    ]
