# Generated by Django 6.0.7 on 2026-07-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_clasificaciongrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('OCTAVOS', 'Octavos'), ('CUARTOS', 'Cuartos'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competencia')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llaves_ganadas', to='core.participantetemporada')),
                ('participante_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llaves_1', to='core.participantetemporada')),
                ('participante_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llaves_2', to='core.participantetemporada')),
            ],
            options={
                'verbose_name': 'Llave Competencia',
                'verbose_name_plural': 'Llaves Competencia',
            },
        ),
    ]
