# Generated by Django 6.0.7 on 2026-07-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_llavecompetencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='llavecompetencia',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
