# Generated by Django 6.0.7 on 2026-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_llavecompetencia_resuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificaciongrupo',
            name='resultado',
            field=models.CharField(choices=[('CLASIFICADO', 'Clasificado'), ('MEJOR_TERCERO', 'Mejor tercero'), ('ELIMINADO', 'Eliminado')], max_length=20),
        ),
    ]
