# Generated by Django 6.0.7 on 2026-07-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_clasificaciongrupo_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='llavecompetencia',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.instanciacompetencia'),
        ),
    ]
